safe: true
lsi: true
pygments: false
base: http://k1000.github.com/meriling/
title: Comunidad Dzogchen de Canarias
navigation:
  - text: Home
    url: /index.html
  - text: Archive
    url: /archive.html
  - text: Imprint
    url: /imprint.html
profiles:
  - label: google+
    url: https://plus.google.com/102721572594228637143/posts
  - label: facebook
    url: https://www.facebook.com/meriling
  - label: twitter
    url: https://www.facebook.com/merilingtenerife
  - label: YouTube
    url: https://www.youtube.com/user/meriling
disqus:author:
  name: Meriling
  email: kamil.azul@meriling.es
  nick: meriling
  config:
    - label: disqus_shortname
      value: 'havvgsplayground'
googleanalytics:
  account: UA-738346-7